### ISSUE TITLE
Feedback about Spork's dependency management 

### ISSUE THREAD

**Issue by imjhonny** [KTH/spork#184]
Hello, we built a [tool to identify bloated dependencies](https://github.com/castor-software/depclean) on Java dev trees.

DepClean was used on Spork's codebase and built a visual rendering of all the project's dependencies.

We would love it if you could take 7min of your time to look at this rendering and provide feedback.

If you are interested you can go to [this link](https://haqc929te3d.typeform.com/to/Y9t0v0mO)

Thanks a lot

DepClean team

**Comment by slarse** [comment]
@imjhonny Of course I'll help!

On a side note, I believe that there's a bug here. The project view lists `junit-jupiter` as unused, but it's most definitely used in the tests. I can't remove it as a direct dependency as I will then not be able to compile the tests.

Any idea of what's going on there?

**Comment by imjhonny** [comment]
@slarse Thank you for your time and feedback!

After checking the junit-jupiter dependency, I noticed that the dependency contains a feature of java-9 and newer versions called _module-info_. The dependency itself has no other type than module-info that adds the dependencies used in the project. 

We will check the case for the module-info feature and modify the tool. 

Thank you for pointing it.

**Comment by slarse** [comment]
> The dependency itself has no other type than module-info that adds the dependencies used in the project.

Ah, I see, interesting! I must admit that I've not quite kept up-to-speed with all of the "new" Java 9+ features.

Closing this issue now, thanks for the insights!
